#!/data/data/com.termux/files/usr/bin/bash
# ============================================================
# TermuxHost — Setup Script
# Run from inside artifacts/api-server/:
#   bash setup.sh
# ============================================================

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DIST="$SCRIPT_DIR/dist/index.mjs"
ENV_FILE="$SCRIPT_DIR/.env"

echo ""
echo "======================================"
echo "  TermuxHost — Termux Setup"
echo "  Project: $SCRIPT_DIR"
echo "======================================"
echo ""

# ── Node.js ────────────────────────────────────────────────
if ! command -v node &>/dev/null; then
  echo "[*] Installing Node.js..."
  pkg install nodejs -y
fi
NODE_VER=$(node --version | cut -c2- | cut -d. -f1)
if [ "$NODE_VER" -lt 18 ]; then
  echo "[!] Node.js v18+ required. Got: $(node --version)"
  echo "    Run: pkg install nodejs"
  exit 1
fi
echo "[✓] Node.js $(node --version)"

# ── Python (optional) ──────────────────────────────────────
if command -v python3 &>/dev/null || command -v python &>/dev/null; then
  echo "[✓] Python available"
else
  echo "[~] Python not found — install with: pkg install python"
fi

# ── PM2 ────────────────────────────────────────────────────
if ! command -v pm2 &>/dev/null; then
  echo "[*] Installing PM2..."
  npm install -g pm2
fi
echo "[✓] PM2 $(pm2 --version)"

# ── Runtime + build packages ───────────────────────────────
echo "[*] Installing dependencies (nodemailer, esbuild, pino plugin)..."
cd "$SCRIPT_DIR/termux"
npm install --ignore-scripts 2>&1 | grep -v "^npm warn" || true
cd "$SCRIPT_DIR"
echo "[✓] Dependencies installed"

# ── Build if dist is missing ───────────────────────────────
if [ ! -f "$DIST" ]; then
  echo ""
  echo "[!] dist/index.mjs not found — building from source..."
  echo "    (This takes ~30 seconds on first run)"
  echo ""
  node "$SCRIPT_DIR/termux-build.mjs"
  echo ""
  if [ ! -f "$DIST" ]; then
    echo "[!] Build failed. Check errors above."
    exit 1
  fi
  echo "[✓] Build successful"
else
  echo "[✓] Server bundle: $DIST"
fi

# ── .env ───────────────────────────────────────────────────
if [ ! -f "$ENV_FILE" ]; then
  cp "$SCRIPT_DIR/.env.example" "$ENV_FILE"
  echo ""
  echo "[!] Created .env at: $ENV_FILE"
  echo "    Required values to fill in:"
  echo "      DATABASE_URL  = postgresql://...?sslmode=require"
  echo "      JWT_SECRET    = run: openssl rand -hex 32"
  echo "      PORT          = 3000"
  echo "      EMAIL_USER    = your@gmail.com"
  echo "      EMAIL_PASS    = 16-char Gmail App Password"
  echo ""
  echo "    Edit now:  nano $ENV_FILE"
else
  echo "[✓] .env exists"
fi

# ── Termux:Boot script ─────────────────────────────────────
BOOT_DIR="$HOME/.termux/boot"
mkdir -p "$BOOT_DIR"
cat > "$BOOT_DIR/termuxhost.sh" << BOOTEOF
#!/data/data/com.termux/files/usr/bin/bash
# Auto-start TermuxHost on device reboot (requires Termux:Boot from F-Droid)
pm2 resurrect
BOOTEOF
chmod +x "$BOOT_DIR/termuxhost.sh"
echo "[✓] Boot script: ~/.termux/boot/termuxhost.sh"

# ── Write start.sh with correct path ──────────────────────
cat > "$SCRIPT_DIR/start.sh" << STARTEOF
#!/data/data/com.termux/files/usr/bin/bash
# Generated by setup.sh
# Uses Node.js built-in --env-file flag (v20.6+) so .env loads before any code runs.
DIST="$DIST"
ENV_FILE="$ENV_FILE"

pm2 delete termuxhost-api 2>/dev/null || true
pm2 start "\$DIST" --name termuxhost-api --node-args="--env-file=\$ENV_FILE"
pm2 save
STARTEOF
chmod +x "$SCRIPT_DIR/start.sh"
echo "[✓] start.sh written"

# ── Done ───────────────────────────────────────────────────
echo ""
echo "======================================"
echo "  Setup Complete!"
echo "======================================"
echo ""
echo "  1. Edit your config:"
echo "     nano $ENV_FILE"
echo ""
echo "  2. Start the server (use THIS exact command — path is auto-set):"
echo "     bash $SCRIPT_DIR/start.sh"
echo ""
echo "     OR copy-paste this:"
echo "     pm2 start $DIST --name termuxhost-api && pm2 save"
echo ""
echo "  3. Test it:"
echo "     curl http://localhost:3000/api/healthz"
echo ""
echo "  4. Auto-start on device reboot:"
echo "     Install 'Termux:Boot' from F-Droid (boot script already saved)"
echo ""
